services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5500:5500"
    environment:
      PORT: 5500
      DATABASE_URL: ${DATABASE_URL}
      DIRECT_URL: ${DIRECT_URL}
      PINECONE_API_KEY: ${PINECONE_API_KEY}
      PINECONE_INDEX_NAME: ${PINECONE_INDEX_NAME}
      VOYAGE_API_KEY: ${VOYAGE_API_KEY}
      AI_PROVIDER_API_KEY: ${AI_PROVIDER_API_KEY}

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://localhost:5500/api
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"
